CREATE TABLE TUSER
(
     U_ID     VARCHAR2(20)   NOT  NULL  PRIMARY KEY    
   , U_PW   VARCHAR2(60) NOT  NULL
   , U_NAME   VARCHAR2(60)  NOT  NULL
   , U_AGE      NUMBER(4)   NOT NULL
   , U_GENDER   NUMBER(2)   NOT NULL
   , U_TEL      VARCHAR(2)  NOT NULL
)

CREATE TABLE SIGHT
(
     S_NAME     VARCHAR2(50)   NOT  NULL  PRIMARY KEY    
   , S_ADDRESS   VARCHAR2(200) NOT  NULL
   , S_FEE   VARCHAR2(10)    NULL
   , S_TEL      VARCHAR2(15)   NULL
   , S_HP   VARCHAR2(200)   NULL
   
)

CREATE TABLE FESTIVAL
(
     F_NAME      VARCHAR2(50)      NOT  NULL  PRIMARY KEY    
   , F_DATE      DATE              NOT NULL
   , F_ADDRESS   VARCHAR2(200)     NOT  NULL
   , F_FEE       VARCHAR2(11)      NULL
   , F_TEL       VARCHAR2(15)      NULL
   , F_HP        VARCHAR2(200)     NULL
   
)
